/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ShiftManagementRouteImport } from './routes/shift-management'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchReservationsRouteImport } from './routes/search-reservations'
import { Route as SearchInvoiceRouteImport } from './routes/search-invoice'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as RoomTypesRouteImport } from './routes/room-types'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReportQueueRouteImport } from './routes/report-queue'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RecentlyViewedRouteImport } from './routes/recently-viewed'
import { Route as RatePlansRouteImport } from './routes/rate-plans'
import { Route as RateOverridesRouteImport } from './routes/rate-overrides'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductInventoryRouteImport } from './routes/product-inventory'
import { Route as PrintLogRouteImport } from './routes/print-log'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as OpenFoliosRouteImport } from './routes/open-folios'
import { Route as NightAuditRouteImport } from './routes/night-audit'
import { Route as MyHousekeepingRouteImport } from './routes/my-housekeeping'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LostFoundRouteImport } from './routes/lost-found'
import { Route as InHouseRouteImport } from './routes/in-house'
import { Route as HousekeepingRouteImport } from './routes/housekeeping'
import { Route as HouseInventoryRouteImport } from './routes/house-inventory'
import { Route as HouseAccountsRouteImport } from './routes/house-accounts'
import { Route as GuestsRouteImport } from './routes/guests'
import { Route as GroupMasterRouteImport } from './routes/group-master'
import { Route as DiscountCodesRouteImport } from './routes/discount-codes'
import { Route as DeparturesRouteImport } from './routes/departures'
import { Route as CreditNotesRouteImport } from './routes/credit-notes'
import { Route as BatchProcessRouteImport } from './routes/batch-process'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ArrivalsRouteImport } from './routes/arrivals'
import { Route as ArchivedReservationsRouteImport } from './routes/archived-reservations'
import { Route as AdvanceDepositsRouteImport } from './routes/advance-deposits'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsUserActivityRouteImport } from './routes/reports.user-activity'
import { Route as PrintShiftShiftIdRouteImport } from './routes/print-shift.$shiftId'
import { Route as PrintReceiptReservationIdRouteImport } from './routes/print-receipt.$reservationId'
import { Route as PrintInvoiceReservationIdRouteImport } from './routes/print-invoice.$reservationId'
import { Route as PrintCreditNoteNoteIdRouteImport } from './routes/print-credit-note.$noteId'
import { Route as GuestGuestIdRouteImport } from './routes/guest.$guestId'
import { Route as BulkRoutingSetupRouteImport } from './routes/bulk-routing.setup'
import { Route as BulkRoutingFastPostingRouteImport } from './routes/bulk-routing.fast-posting'
import { Route as PrintHousekeepingSummaryRouteImport } from './routes/print.housekeeping.summary'
import { Route as PrintHousekeepingByFloorRouteImport } from './routes/print.housekeeping.by-floor'
import { Route as PrintHousekeepingAllRouteImport } from './routes/print.housekeeping.all'
import { Route as PrintHousekeeperReportReportIdRouteImport } from './routes/print.housekeeper-report.$reportId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftManagementRoute = ShiftManagementRouteImport.update({
  id: '/shift-management',
  path: '/shift-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchReservationsRoute = SearchReservationsRouteImport.update({
  id: '/search-reservations',
  path: '/search-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchInvoiceRoute = SearchInvoiceRouteImport.update({
  id: '/search-invoice',
  path: '/search-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomTypesRoute = RoomTypesRouteImport.update({
  id: '/room-types',
  path: '/room-types',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportQueueRoute = ReportQueueRouteImport.update({
  id: '/report-queue',
  path: '/report-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentlyViewedRoute = RecentlyViewedRouteImport.update({
  id: '/recently-viewed',
  path: '/recently-viewed',
  getParentRoute: () => rootRouteImport,
} as any)
const RatePlansRoute = RatePlansRouteImport.update({
  id: '/rate-plans',
  path: '/rate-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const RateOverridesRoute = RateOverridesRouteImport.update({
  id: '/rate-overrides',
  path: '/rate-overrides',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductInventoryRoute = ProductInventoryRouteImport.update({
  id: '/product-inventory',
  path: '/product-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintLogRoute = PrintLogRouteImport.update({
  id: '/print-log',
  path: '/print-log',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenFoliosRoute = OpenFoliosRouteImport.update({
  id: '/open-folios',
  path: '/open-folios',
  getParentRoute: () => rootRouteImport,
} as any)
const NightAuditRoute = NightAuditRouteImport.update({
  id: '/night-audit',
  path: '/night-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const MyHousekeepingRoute = MyHousekeepingRouteImport.update({
  id: '/my-housekeeping',
  path: '/my-housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LostFoundRoute = LostFoundRouteImport.update({
  id: '/lost-found',
  path: '/lost-found',
  getParentRoute: () => rootRouteImport,
} as any)
const InHouseRoute = InHouseRouteImport.update({
  id: '/in-house',
  path: '/in-house',
  getParentRoute: () => rootRouteImport,
} as any)
const HousekeepingRoute = HousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseInventoryRoute = HouseInventoryRouteImport.update({
  id: '/house-inventory',
  path: '/house-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseAccountsRoute = HouseAccountsRouteImport.update({
  id: '/house-accounts',
  path: '/house-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestsRoute = GuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupMasterRoute = GroupMasterRouteImport.update({
  id: '/group-master',
  path: '/group-master',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountCodesRoute = DiscountCodesRouteImport.update({
  id: '/discount-codes',
  path: '/discount-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeparturesRoute = DeparturesRouteImport.update({
  id: '/departures',
  path: '/departures',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditNotesRoute = CreditNotesRouteImport.update({
  id: '/credit-notes',
  path: '/credit-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchProcessRoute = BatchProcessRouteImport.update({
  id: '/batch-process',
  path: '/batch-process',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrivalsRoute = ArrivalsRouteImport.update({
  id: '/arrivals',
  path: '/arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivedReservationsRoute = ArchivedReservationsRouteImport.update({
  id: '/archived-reservations',
  path: '/archived-reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvanceDepositsRoute = AdvanceDepositsRouteImport.update({
  id: '/advance-deposits',
  path: '/advance-deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsUserActivityRoute = ReportsUserActivityRouteImport.update({
  id: '/user-activity',
  path: '/user-activity',
  getParentRoute: () => ReportsRoute,
} as any)
const PrintShiftShiftIdRoute = PrintShiftShiftIdRouteImport.update({
  id: '/print-shift/$shiftId',
  path: '/print-shift/$shiftId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintReceiptReservationIdRoute =
  PrintReceiptReservationIdRouteImport.update({
    id: '/print-receipt/$reservationId',
    path: '/print-receipt/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintInvoiceReservationIdRoute =
  PrintInvoiceReservationIdRouteImport.update({
    id: '/print-invoice/$reservationId',
    path: '/print-invoice/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintCreditNoteNoteIdRoute = PrintCreditNoteNoteIdRouteImport.update({
  id: '/print-credit-note/$noteId',
  path: '/print-credit-note/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestGuestIdRoute = GuestGuestIdRouteImport.update({
  id: '/guest/$guestId',
  path: '/guest/$guestId',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoutingSetupRoute = BulkRoutingSetupRouteImport.update({
  id: '/bulk-routing/setup',
  path: '/bulk-routing/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoutingFastPostingRoute = BulkRoutingFastPostingRouteImport.update({
  id: '/bulk-routing/fast-posting',
  path: '/bulk-routing/fast-posting',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintHousekeepingSummaryRoute =
  PrintHousekeepingSummaryRouteImport.update({
    id: '/print/housekeeping/summary',
    path: '/print/housekeeping/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintHousekeepingByFloorRoute =
  PrintHousekeepingByFloorRouteImport.update({
    id: '/print/housekeeping/by-floor',
    path: '/print/housekeeping/by-floor',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintHousekeepingAllRoute = PrintHousekeepingAllRouteImport.update({
  id: '/print/housekeeping/all',
  path: '/print/housekeeping/all',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintHousekeeperReportReportIdRoute =
  PrintHousekeeperReportReportIdRouteImport.update({
    id: '/print/housekeeper-report/$reportId',
    path: '/print/housekeeper-report/$reportId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advance-deposits': typeof AdvanceDepositsRoute
  '/archived-reservations': typeof ArchivedReservationsRoute
  '/arrivals': typeof ArrivalsRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/batch-process': typeof BatchProcessRoute
  '/credit-notes': typeof CreditNotesRoute
  '/departures': typeof DeparturesRoute
  '/discount-codes': typeof DiscountCodesRoute
  '/group-master': typeof GroupMasterRoute
  '/guests': typeof GuestsRoute
  '/house-accounts': typeof HouseAccountsRoute
  '/house-inventory': typeof HouseInventoryRoute
  '/housekeeping': typeof HousekeepingRoute
  '/in-house': typeof InHouseRoute
  '/lost-found': typeof LostFoundRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-housekeeping': typeof MyHousekeepingRoute
  '/night-audit': typeof NightAuditRoute
  '/open-folios': typeof OpenFoliosRoute
  '/payments': typeof PaymentsRoute
  '/print-log': typeof PrintLogRoute
  '/product-inventory': typeof ProductInventoryRoute
  '/profile': typeof ProfileRoute
  '/rate-overrides': typeof RateOverridesRoute
  '/rate-plans': typeof RatePlansRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/reminders': typeof RemindersRoute
  '/report-queue': typeof ReportQueueRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/room-types': typeof RoomTypesRoute
  '/rooms': typeof RoomsRoute
  '/search-invoice': typeof SearchInvoiceRoute
  '/search-reservations': typeof SearchReservationsRoute
  '/settings': typeof SettingsRoute
  '/shift-management': typeof ShiftManagementRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/bulk-routing/fast-posting': typeof BulkRoutingFastPostingRoute
  '/bulk-routing/setup': typeof BulkRoutingSetupRoute
  '/guest/$guestId': typeof GuestGuestIdRoute
  '/print-credit-note/$noteId': typeof PrintCreditNoteNoteIdRoute
  '/print-invoice/$reservationId': typeof PrintInvoiceReservationIdRoute
  '/print-receipt/$reservationId': typeof PrintReceiptReservationIdRoute
  '/print-shift/$shiftId': typeof PrintShiftShiftIdRoute
  '/reports/user-activity': typeof ReportsUserActivityRoute
  '/print/housekeeper-report/$reportId': typeof PrintHousekeeperReportReportIdRoute
  '/print/housekeeping/all': typeof PrintHousekeepingAllRoute
  '/print/housekeeping/by-floor': typeof PrintHousekeepingByFloorRoute
  '/print/housekeeping/summary': typeof PrintHousekeepingSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advance-deposits': typeof AdvanceDepositsRoute
  '/archived-reservations': typeof ArchivedReservationsRoute
  '/arrivals': typeof ArrivalsRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/batch-process': typeof BatchProcessRoute
  '/credit-notes': typeof CreditNotesRoute
  '/departures': typeof DeparturesRoute
  '/discount-codes': typeof DiscountCodesRoute
  '/group-master': typeof GroupMasterRoute
  '/guests': typeof GuestsRoute
  '/house-accounts': typeof HouseAccountsRoute
  '/house-inventory': typeof HouseInventoryRoute
  '/housekeeping': typeof HousekeepingRoute
  '/in-house': typeof InHouseRoute
  '/lost-found': typeof LostFoundRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-housekeeping': typeof MyHousekeepingRoute
  '/night-audit': typeof NightAuditRoute
  '/open-folios': typeof OpenFoliosRoute
  '/payments': typeof PaymentsRoute
  '/print-log': typeof PrintLogRoute
  '/product-inventory': typeof ProductInventoryRoute
  '/profile': typeof ProfileRoute
  '/rate-overrides': typeof RateOverridesRoute
  '/rate-plans': typeof RatePlansRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/reminders': typeof RemindersRoute
  '/report-queue': typeof ReportQueueRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/room-types': typeof RoomTypesRoute
  '/rooms': typeof RoomsRoute
  '/search-invoice': typeof SearchInvoiceRoute
  '/search-reservations': typeof SearchReservationsRoute
  '/settings': typeof SettingsRoute
  '/shift-management': typeof ShiftManagementRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/bulk-routing/fast-posting': typeof BulkRoutingFastPostingRoute
  '/bulk-routing/setup': typeof BulkRoutingSetupRoute
  '/guest/$guestId': typeof GuestGuestIdRoute
  '/print-credit-note/$noteId': typeof PrintCreditNoteNoteIdRoute
  '/print-invoice/$reservationId': typeof PrintInvoiceReservationIdRoute
  '/print-receipt/$reservationId': typeof PrintReceiptReservationIdRoute
  '/print-shift/$shiftId': typeof PrintShiftShiftIdRoute
  '/reports/user-activity': typeof ReportsUserActivityRoute
  '/print/housekeeper-report/$reportId': typeof PrintHousekeeperReportReportIdRoute
  '/print/housekeeping/all': typeof PrintHousekeepingAllRoute
  '/print/housekeeping/by-floor': typeof PrintHousekeepingByFloorRoute
  '/print/housekeeping/summary': typeof PrintHousekeepingSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advance-deposits': typeof AdvanceDepositsRoute
  '/archived-reservations': typeof ArchivedReservationsRoute
  '/arrivals': typeof ArrivalsRoute
  '/audit': typeof AuditRoute
  '/availability': typeof AvailabilityRoute
  '/batch-process': typeof BatchProcessRoute
  '/credit-notes': typeof CreditNotesRoute
  '/departures': typeof DeparturesRoute
  '/discount-codes': typeof DiscountCodesRoute
  '/group-master': typeof GroupMasterRoute
  '/guests': typeof GuestsRoute
  '/house-accounts': typeof HouseAccountsRoute
  '/house-inventory': typeof HouseInventoryRoute
  '/housekeeping': typeof HousekeepingRoute
  '/in-house': typeof InHouseRoute
  '/lost-found': typeof LostFoundRoute
  '/maintenance': typeof MaintenanceRoute
  '/my-housekeeping': typeof MyHousekeepingRoute
  '/night-audit': typeof NightAuditRoute
  '/open-folios': typeof OpenFoliosRoute
  '/payments': typeof PaymentsRoute
  '/print-log': typeof PrintLogRoute
  '/product-inventory': typeof ProductInventoryRoute
  '/profile': typeof ProfileRoute
  '/rate-overrides': typeof RateOverridesRoute
  '/rate-plans': typeof RatePlansRoute
  '/recently-viewed': typeof RecentlyViewedRoute
  '/reminders': typeof RemindersRoute
  '/report-queue': typeof ReportQueueRoute
  '/reports': typeof ReportsRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/room-types': typeof RoomTypesRoute
  '/rooms': typeof RoomsRoute
  '/search-invoice': typeof SearchInvoiceRoute
  '/search-reservations': typeof SearchReservationsRoute
  '/settings': typeof SettingsRoute
  '/shift-management': typeof ShiftManagementRoute
  '/templates': typeof TemplatesRoute
  '/users': typeof UsersRoute
  '/bulk-routing/fast-posting': typeof BulkRoutingFastPostingRoute
  '/bulk-routing/setup': typeof BulkRoutingSetupRoute
  '/guest/$guestId': typeof GuestGuestIdRoute
  '/print-credit-note/$noteId': typeof PrintCreditNoteNoteIdRoute
  '/print-invoice/$reservationId': typeof PrintInvoiceReservationIdRoute
  '/print-receipt/$reservationId': typeof PrintReceiptReservationIdRoute
  '/print-shift/$shiftId': typeof PrintShiftShiftIdRoute
  '/reports/user-activity': typeof ReportsUserActivityRoute
  '/print/housekeeper-report/$reportId': typeof PrintHousekeeperReportReportIdRoute
  '/print/housekeeping/all': typeof PrintHousekeepingAllRoute
  '/print/housekeeping/by-floor': typeof PrintHousekeepingByFloorRoute
  '/print/housekeeping/summary': typeof PrintHousekeepingSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advance-deposits'
    | '/archived-reservations'
    | '/arrivals'
    | '/audit'
    | '/availability'
    | '/batch-process'
    | '/credit-notes'
    | '/departures'
    | '/discount-codes'
    | '/group-master'
    | '/guests'
    | '/house-accounts'
    | '/house-inventory'
    | '/housekeeping'
    | '/in-house'
    | '/lost-found'
    | '/maintenance'
    | '/my-housekeeping'
    | '/night-audit'
    | '/open-folios'
    | '/payments'
    | '/print-log'
    | '/product-inventory'
    | '/profile'
    | '/rate-overrides'
    | '/rate-plans'
    | '/recently-viewed'
    | '/reminders'
    | '/report-queue'
    | '/reports'
    | '/reservations'
    | '/room-types'
    | '/rooms'
    | '/search-invoice'
    | '/search-reservations'
    | '/settings'
    | '/shift-management'
    | '/templates'
    | '/users'
    | '/bulk-routing/fast-posting'
    | '/bulk-routing/setup'
    | '/guest/$guestId'
    | '/print-credit-note/$noteId'
    | '/print-invoice/$reservationId'
    | '/print-receipt/$reservationId'
    | '/print-shift/$shiftId'
    | '/reports/user-activity'
    | '/print/housekeeper-report/$reportId'
    | '/print/housekeeping/all'
    | '/print/housekeeping/by-floor'
    | '/print/housekeeping/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advance-deposits'
    | '/archived-reservations'
    | '/arrivals'
    | '/audit'
    | '/availability'
    | '/batch-process'
    | '/credit-notes'
    | '/departures'
    | '/discount-codes'
    | '/group-master'
    | '/guests'
    | '/house-accounts'
    | '/house-inventory'
    | '/housekeeping'
    | '/in-house'
    | '/lost-found'
    | '/maintenance'
    | '/my-housekeeping'
    | '/night-audit'
    | '/open-folios'
    | '/payments'
    | '/print-log'
    | '/product-inventory'
    | '/profile'
    | '/rate-overrides'
    | '/rate-plans'
    | '/recently-viewed'
    | '/reminders'
    | '/report-queue'
    | '/reports'
    | '/reservations'
    | '/room-types'
    | '/rooms'
    | '/search-invoice'
    | '/search-reservations'
    | '/settings'
    | '/shift-management'
    | '/templates'
    | '/users'
    | '/bulk-routing/fast-posting'
    | '/bulk-routing/setup'
    | '/guest/$guestId'
    | '/print-credit-note/$noteId'
    | '/print-invoice/$reservationId'
    | '/print-receipt/$reservationId'
    | '/print-shift/$shiftId'
    | '/reports/user-activity'
    | '/print/housekeeper-report/$reportId'
    | '/print/housekeeping/all'
    | '/print/housekeeping/by-floor'
    | '/print/housekeeping/summary'
  id:
    | '__root__'
    | '/'
    | '/advance-deposits'
    | '/archived-reservations'
    | '/arrivals'
    | '/audit'
    | '/availability'
    | '/batch-process'
    | '/credit-notes'
    | '/departures'
    | '/discount-codes'
    | '/group-master'
    | '/guests'
    | '/house-accounts'
    | '/house-inventory'
    | '/housekeeping'
    | '/in-house'
    | '/lost-found'
    | '/maintenance'
    | '/my-housekeeping'
    | '/night-audit'
    | '/open-folios'
    | '/payments'
    | '/print-log'
    | '/product-inventory'
    | '/profile'
    | '/rate-overrides'
    | '/rate-plans'
    | '/recently-viewed'
    | '/reminders'
    | '/report-queue'
    | '/reports'
    | '/reservations'
    | '/room-types'
    | '/rooms'
    | '/search-invoice'
    | '/search-reservations'
    | '/settings'
    | '/shift-management'
    | '/templates'
    | '/users'
    | '/bulk-routing/fast-posting'
    | '/bulk-routing/setup'
    | '/guest/$guestId'
    | '/print-credit-note/$noteId'
    | '/print-invoice/$reservationId'
    | '/print-receipt/$reservationId'
    | '/print-shift/$shiftId'
    | '/reports/user-activity'
    | '/print/housekeeper-report/$reportId'
    | '/print/housekeeping/all'
    | '/print/housekeeping/by-floor'
    | '/print/housekeeping/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvanceDepositsRoute: typeof AdvanceDepositsRoute
  ArchivedReservationsRoute: typeof ArchivedReservationsRoute
  ArrivalsRoute: typeof ArrivalsRoute
  AuditRoute: typeof AuditRoute
  AvailabilityRoute: typeof AvailabilityRoute
  BatchProcessRoute: typeof BatchProcessRoute
  CreditNotesRoute: typeof CreditNotesRoute
  DeparturesRoute: typeof DeparturesRoute
  DiscountCodesRoute: typeof DiscountCodesRoute
  GroupMasterRoute: typeof GroupMasterRoute
  GuestsRoute: typeof GuestsRoute
  HouseAccountsRoute: typeof HouseAccountsRoute
  HouseInventoryRoute: typeof HouseInventoryRoute
  HousekeepingRoute: typeof HousekeepingRoute
  InHouseRoute: typeof InHouseRoute
  LostFoundRoute: typeof LostFoundRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MyHousekeepingRoute: typeof MyHousekeepingRoute
  NightAuditRoute: typeof NightAuditRoute
  OpenFoliosRoute: typeof OpenFoliosRoute
  PaymentsRoute: typeof PaymentsRoute
  PrintLogRoute: typeof PrintLogRoute
  ProductInventoryRoute: typeof ProductInventoryRoute
  ProfileRoute: typeof ProfileRoute
  RateOverridesRoute: typeof RateOverridesRoute
  RatePlansRoute: typeof RatePlansRoute
  RecentlyViewedRoute: typeof RecentlyViewedRoute
  RemindersRoute: typeof RemindersRoute
  ReportQueueRoute: typeof ReportQueueRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ReservationsRoute: typeof ReservationsRoute
  RoomTypesRoute: typeof RoomTypesRoute
  RoomsRoute: typeof RoomsRoute
  SearchInvoiceRoute: typeof SearchInvoiceRoute
  SearchReservationsRoute: typeof SearchReservationsRoute
  SettingsRoute: typeof SettingsRoute
  ShiftManagementRoute: typeof ShiftManagementRoute
  TemplatesRoute: typeof TemplatesRoute
  UsersRoute: typeof UsersRoute
  BulkRoutingFastPostingRoute: typeof BulkRoutingFastPostingRoute
  BulkRoutingSetupRoute: typeof BulkRoutingSetupRoute
  GuestGuestIdRoute: typeof GuestGuestIdRoute
  PrintCreditNoteNoteIdRoute: typeof PrintCreditNoteNoteIdRoute
  PrintInvoiceReservationIdRoute: typeof PrintInvoiceReservationIdRoute
  PrintReceiptReservationIdRoute: typeof PrintReceiptReservationIdRoute
  PrintShiftShiftIdRoute: typeof PrintShiftShiftIdRoute
  PrintHousekeeperReportReportIdRoute: typeof PrintHousekeeperReportReportIdRoute
  PrintHousekeepingAllRoute: typeof PrintHousekeepingAllRoute
  PrintHousekeepingByFloorRoute: typeof PrintHousekeepingByFloorRoute
  PrintHousekeepingSummaryRoute: typeof PrintHousekeepingSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift-management': {
      id: '/shift-management'
      path: '/shift-management'
      fullPath: '/shift-management'
      preLoaderRoute: typeof ShiftManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-reservations': {
      id: '/search-reservations'
      path: '/search-reservations'
      fullPath: '/search-reservations'
      preLoaderRoute: typeof SearchReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-invoice': {
      id: '/search-invoice'
      path: '/search-invoice'
      fullPath: '/search-invoice'
      preLoaderRoute: typeof SearchInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room-types': {
      id: '/room-types'
      path: '/room-types'
      fullPath: '/room-types'
      preLoaderRoute: typeof RoomTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-queue': {
      id: '/report-queue'
      path: '/report-queue'
      fullPath: '/report-queue'
      preLoaderRoute: typeof ReportQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recently-viewed': {
      id: '/recently-viewed'
      path: '/recently-viewed'
      fullPath: '/recently-viewed'
      preLoaderRoute: typeof RecentlyViewedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-plans': {
      id: '/rate-plans'
      path: '/rate-plans'
      fullPath: '/rate-plans'
      preLoaderRoute: typeof RatePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-overrides': {
      id: '/rate-overrides'
      path: '/rate-overrides'
      fullPath: '/rate-overrides'
      preLoaderRoute: typeof RateOverridesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-inventory': {
      id: '/product-inventory'
      path: '/product-inventory'
      fullPath: '/product-inventory'
      preLoaderRoute: typeof ProductInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-log': {
      id: '/print-log'
      path: '/print-log'
      fullPath: '/print-log'
      preLoaderRoute: typeof PrintLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-folios': {
      id: '/open-folios'
      path: '/open-folios'
      fullPath: '/open-folios'
      preLoaderRoute: typeof OpenFoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night-audit': {
      id: '/night-audit'
      path: '/night-audit'
      fullPath: '/night-audit'
      preLoaderRoute: typeof NightAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-housekeeping': {
      id: '/my-housekeeping'
      path: '/my-housekeeping'
      fullPath: '/my-housekeeping'
      preLoaderRoute: typeof MyHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lost-found': {
      id: '/lost-found'
      path: '/lost-found'
      fullPath: '/lost-found'
      preLoaderRoute: typeof LostFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/in-house': {
      id: '/in-house'
      path: '/in-house'
      fullPath: '/in-house'
      preLoaderRoute: typeof InHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housekeeping': {
      id: '/housekeeping'
      path: '/housekeeping'
      fullPath: '/housekeeping'
      preLoaderRoute: typeof HousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-inventory': {
      id: '/house-inventory'
      path: '/house-inventory'
      fullPath: '/house-inventory'
      preLoaderRoute: typeof HouseInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-accounts': {
      id: '/house-accounts'
      path: '/house-accounts'
      fullPath: '/house-accounts'
      preLoaderRoute: typeof HouseAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guests': {
      id: '/guests'
      path: '/guests'
      fullPath: '/guests'
      preLoaderRoute: typeof GuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-master': {
      id: '/group-master'
      path: '/group-master'
      fullPath: '/group-master'
      preLoaderRoute: typeof GroupMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discount-codes': {
      id: '/discount-codes'
      path: '/discount-codes'
      fullPath: '/discount-codes'
      preLoaderRoute: typeof DiscountCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departures': {
      id: '/departures'
      path: '/departures'
      fullPath: '/departures'
      preLoaderRoute: typeof DeparturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credit-notes': {
      id: '/credit-notes'
      path: '/credit-notes'
      fullPath: '/credit-notes'
      preLoaderRoute: typeof CreditNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch-process': {
      id: '/batch-process'
      path: '/batch-process'
      fullPath: '/batch-process'
      preLoaderRoute: typeof BatchProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrivals': {
      id: '/arrivals'
      path: '/arrivals'
      fullPath: '/arrivals'
      preLoaderRoute: typeof ArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archived-reservations': {
      id: '/archived-reservations'
      path: '/archived-reservations'
      fullPath: '/archived-reservations'
      preLoaderRoute: typeof ArchivedReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advance-deposits': {
      id: '/advance-deposits'
      path: '/advance-deposits'
      fullPath: '/advance-deposits'
      preLoaderRoute: typeof AdvanceDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/user-activity': {
      id: '/reports/user-activity'
      path: '/user-activity'
      fullPath: '/reports/user-activity'
      preLoaderRoute: typeof ReportsUserActivityRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/print-shift/$shiftId': {
      id: '/print-shift/$shiftId'
      path: '/print-shift/$shiftId'
      fullPath: '/print-shift/$shiftId'
      preLoaderRoute: typeof PrintShiftShiftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-receipt/$reservationId': {
      id: '/print-receipt/$reservationId'
      path: '/print-receipt/$reservationId'
      fullPath: '/print-receipt/$reservationId'
      preLoaderRoute: typeof PrintReceiptReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-invoice/$reservationId': {
      id: '/print-invoice/$reservationId'
      path: '/print-invoice/$reservationId'
      fullPath: '/print-invoice/$reservationId'
      preLoaderRoute: typeof PrintInvoiceReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-credit-note/$noteId': {
      id: '/print-credit-note/$noteId'
      path: '/print-credit-note/$noteId'
      fullPath: '/print-credit-note/$noteId'
      preLoaderRoute: typeof PrintCreditNoteNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/$guestId': {
      id: '/guest/$guestId'
      path: '/guest/$guestId'
      fullPath: '/guest/$guestId'
      preLoaderRoute: typeof GuestGuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-routing/setup': {
      id: '/bulk-routing/setup'
      path: '/bulk-routing/setup'
      fullPath: '/bulk-routing/setup'
      preLoaderRoute: typeof BulkRoutingSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-routing/fast-posting': {
      id: '/bulk-routing/fast-posting'
      path: '/bulk-routing/fast-posting'
      fullPath: '/bulk-routing/fast-posting'
      preLoaderRoute: typeof BulkRoutingFastPostingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/housekeeping/summary': {
      id: '/print/housekeeping/summary'
      path: '/print/housekeeping/summary'
      fullPath: '/print/housekeeping/summary'
      preLoaderRoute: typeof PrintHousekeepingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/housekeeping/by-floor': {
      id: '/print/housekeeping/by-floor'
      path: '/print/housekeeping/by-floor'
      fullPath: '/print/housekeeping/by-floor'
      preLoaderRoute: typeof PrintHousekeepingByFloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/housekeeping/all': {
      id: '/print/housekeeping/all'
      path: '/print/housekeeping/all'
      fullPath: '/print/housekeeping/all'
      preLoaderRoute: typeof PrintHousekeepingAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/housekeeper-report/$reportId': {
      id: '/print/housekeeper-report/$reportId'
      path: '/print/housekeeper-report/$reportId'
      fullPath: '/print/housekeeper-report/$reportId'
      preLoaderRoute: typeof PrintHousekeeperReportReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsUserActivityRoute: typeof ReportsUserActivityRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsUserActivityRoute: ReportsUserActivityRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvanceDepositsRoute: AdvanceDepositsRoute,
  ArchivedReservationsRoute: ArchivedReservationsRoute,
  ArrivalsRoute: ArrivalsRoute,
  AuditRoute: AuditRoute,
  AvailabilityRoute: AvailabilityRoute,
  BatchProcessRoute: BatchProcessRoute,
  CreditNotesRoute: CreditNotesRoute,
  DeparturesRoute: DeparturesRoute,
  DiscountCodesRoute: DiscountCodesRoute,
  GroupMasterRoute: GroupMasterRoute,
  GuestsRoute: GuestsRoute,
  HouseAccountsRoute: HouseAccountsRoute,
  HouseInventoryRoute: HouseInventoryRoute,
  HousekeepingRoute: HousekeepingRoute,
  InHouseRoute: InHouseRoute,
  LostFoundRoute: LostFoundRoute,
  MaintenanceRoute: MaintenanceRoute,
  MyHousekeepingRoute: MyHousekeepingRoute,
  NightAuditRoute: NightAuditRoute,
  OpenFoliosRoute: OpenFoliosRoute,
  PaymentsRoute: PaymentsRoute,
  PrintLogRoute: PrintLogRoute,
  ProductInventoryRoute: ProductInventoryRoute,
  ProfileRoute: ProfileRoute,
  RateOverridesRoute: RateOverridesRoute,
  RatePlansRoute: RatePlansRoute,
  RecentlyViewedRoute: RecentlyViewedRoute,
  RemindersRoute: RemindersRoute,
  ReportQueueRoute: ReportQueueRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ReservationsRoute: ReservationsRoute,
  RoomTypesRoute: RoomTypesRoute,
  RoomsRoute: RoomsRoute,
  SearchInvoiceRoute: SearchInvoiceRoute,
  SearchReservationsRoute: SearchReservationsRoute,
  SettingsRoute: SettingsRoute,
  ShiftManagementRoute: ShiftManagementRoute,
  TemplatesRoute: TemplatesRoute,
  UsersRoute: UsersRoute,
  BulkRoutingFastPostingRoute: BulkRoutingFastPostingRoute,
  BulkRoutingSetupRoute: BulkRoutingSetupRoute,
  GuestGuestIdRoute: GuestGuestIdRoute,
  PrintCreditNoteNoteIdRoute: PrintCreditNoteNoteIdRoute,
  PrintInvoiceReservationIdRoute: PrintInvoiceReservationIdRoute,
  PrintReceiptReservationIdRoute: PrintReceiptReservationIdRoute,
  PrintShiftShiftIdRoute: PrintShiftShiftIdRoute,
  PrintHousekeeperReportReportIdRoute: PrintHousekeeperReportReportIdRoute,
  PrintHousekeepingAllRoute: PrintHousekeepingAllRoute,
  PrintHousekeepingByFloorRoute: PrintHousekeepingByFloorRoute,
  PrintHousekeepingSummaryRoute: PrintHousekeepingSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
